name: CI
on: 
  push:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
    - run: npm init
    - run: yarn
    - name: Run ESLint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
