name: CI
on: 
  push:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: | 
        npm init -y
        npm install 
        npm install eslint@8.28.0
    - uses: stefanoeb/eslint-action@1.0.2
